In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {"eid":[101,102,103,104],"ename":["Ajay","Vinay","Karan","Seema"],"salary":[14000,45000,36000,56000]}
df = pd.DataFrame(data,index = ['a','b','c','d'])

In [3]:
df

   eid  ename  salary
a  101   Ajay   14000
b  102  Vinay   45000
c  103  Karan   36000
d  104  Seema   56000

In [4]:
d = {"Location":["Pune","Mumbai","Chennai","Nagpur"]}
new_df = pd.DataFrame(d,index = ['a','b','c','d'])

In [5]:
new_df

  Location
a     Pune
b   Mumbai
c  Chennai
d   Nagpur

In [6]:
#Concatenate columnwise
pd.concat([df,new_df],axis=1)

   eid  ename  salary Location
a  101   Ajay   14000     Pune
b  102  Vinay   45000   Mumbai
c  103  Karan   36000  Chennai
d  104  Seema   56000   Nagpur

In [7]:
df

   eid  ename  salary
a  101   Ajay   14000
b  102  Vinay   45000
c  103  Karan   36000
d  104  Seema   56000

In [8]:
df["annual_salary"] = df["salary"]*12

In [9]:
df

   eid  ename  salary  annual_salary
a  101   Ajay   14000         168000
b  102  Vinay   45000         540000
c  103  Karan   36000         432000
d  104  Seema   56000         672000

In [16]:
df.iloc[2] = [105, "Preeti", 35000, "Programmer"]

In [17]:
df

   eid   ename  salary annual_salary
a  101    Ajay   14000        168000
b  102   Vinay   45000        540000
c  105  Preeti   35000    Programmer
d  104   Seema   56000        672000

## Add new record

In [18]:
df.loc['e'] = [105,"Preeti",35000,"Programmer"]

In [16]:
df

   eid  ename  salary  annual_salary
a  101   Ajay   14000         168000
b  102  Vinay   45000         540000
c  103  Karan   36000         432000
d  104  Seema   56000         672000

In [19]:
data = {"eid":[106,107,108,109],"ename":["Dinesh","Rohit","Teena","Kiran"],"salary":[14000,45000,36000,56000],
        'location':['Pune',"Pune","Mumbai","Mumbai"]}
df_1 = pd.DataFrame(data,index = ['f','g','h','i'])

In [20]:
df_1

   eid   ename  salary location
f  106  Dinesh   14000     Pune
g  107   Rohit   45000     Pune
h  108   Teena   36000   Mumbai
i  109   Kiran   56000   Mumbai

In [21]:
df_1["annual_salary"] = df_1["salary"]*12

In [23]:

df_1

   eid   ename  salary location  annual_salary
f  106  Dinesh   14000     Pune         168000
g  107   Rohit   45000     Pune         540000
h  108   Teena   36000   Mumbai         432000
i  109   Kiran   56000   Mumbai         672000

In [24]:
#Concatenate rowwise
df_combined = pd.concat([df,df_1],axis=0)

In [25]:
df_combined

   eid   ename  salary annual_salary location
a  101    Ajay   14000        168000      NaN
b  102   Vinay   45000        540000      NaN
c  105  Preeti   35000    Programmer      NaN
d  104   Seema   56000        672000      NaN
e  105  Preeti   35000    Programmer      NaN
f  106  Dinesh   14000        168000     Pune
g  107   Rohit   45000        540000     Pune
h  108   Teena   36000        432000   Mumbai
i  109   Kiran   56000        672000   Mumbai

In [29]:
#To delete the row

#df_combined.drop('f',axis=0)
#df_combined.drop('f') #data is deleted and a new object is created, original is not modified
# df_combined.drop('f',inplace=True) #row is deleted from existing object, new object is not created


print(df_combined.index)

Index(['a', 'b', 'c', 'd', 'e', 'g', 'h', 'i'], dtype='object')

In [30]:
df_combined

   eid   ename  salary annual_salary location
a  101    Ajay   14000        168000      NaN
b  102   Vinay   45000        540000      NaN
c  105  Preeti   35000    Programmer      NaN
d  104   Seema   56000        672000      NaN
e  105  Preeti   35000    Programmer      NaN
g  107   Rohit   45000        540000     Pune
h  108   Teena   36000        432000   Mumbai
i  109   Kiran   56000        672000   Mumbai

In [31]:
df_combined

   eid   ename  salary annual_salary location
a  101    Ajay   14000        168000      NaN
b  102   Vinay   45000        540000      NaN
c  105  Preeti   35000    Programmer      NaN
d  104   Seema   56000        672000      NaN
e  105  Preeti   35000    Programmer      NaN
g  107   Rohit   45000        540000     Pune
h  108   Teena   36000        432000   Mumbai
i  109   Kiran   56000        672000   Mumbai

In [32]:
df_combined

   eid   ename  salary annual_salary location
a  101    Ajay   14000        168000      NaN
b  102   Vinay   45000        540000      NaN
c  105  Preeti   35000    Programmer      NaN
d  104   Seema   56000        672000      NaN
e  105  Preeti   35000    Programmer      NaN
g  107   Rohit   45000        540000     Pune
h  108   Teena   36000        432000   Mumbai
i  109   Kiran   56000        672000   Mumbai

In [35]:
df_combined.columns

Index(['eid', 'ename', 'salary', 'annual_salary'], dtype='object')

In [40]:
d = {"Location":["Pune","Mumbai","Chennai","Nagpur"]}

In [41]:
d

{'Location': ['Pune', 'Mumbai', 'Chennai', 'Nagpur']}

In [42]:
'location' != 'Location'

True

In [44]:
print(df_combined.columns)

Index(['eid', 'ename', 'salary', 'annual_salary'], dtype='object')

In [47]:
df_combined.drop(columns=['location'], inplace=True, errors='ignore')

In [65]:
['eid', 'ename', 'salary', 'designation', 'annual_salary', 'location']

['eid', 'ename', 'salary', 'designation', 'annual_salary', 'location']

In [49]:
# Modifying existing data

In [50]:



df_combined.loc['a',"location"]="Pune"
df_combined["location"] = "Pune"

In [51]:
df_combined

   eid   ename  salary annual_salary location
a  101    Ajay   14000        168000     Pune
b  102   Vinay   45000        540000     Pune
c  105  Preeti   35000    Programmer     Pune
d  104   Seema   56000        672000     Pune
e  105  Preeti   35000    Programmer     Pune
g  107   Rohit   45000        540000     Pune
h  108   Teena   36000        432000     Pune
i  109   Kiran   56000        672000     Pune

In [52]:
df_combined.loc[['g','h','i'],"designation"]="Tester"

In [53]:
df_combined

   eid   ename  salary annual_salary location designation
a  101    Ajay   14000        168000     Pune         NaN
b  102   Vinay   45000        540000     Pune         NaN
c  105  Preeti   35000    Programmer     Pune         NaN
d  104   Seema   56000        672000     Pune         NaN
e  105  Preeti   35000    Programmer     Pune         NaN
g  107   Rohit   45000        540000     Pune      Tester
h  108   Teena   36000        432000     Pune      Tester
i  109   Kiran   56000        672000     Pune      Tester

In [54]:

#Display top 5 records
df_combined.head()

   eid   ename  salary annual_salary location designation
a  101    Ajay   14000        168000     Pune         NaN
b  102   Vinay   45000        540000     Pune         NaN
c  105  Preeti   35000    Programmer     Pune         NaN
d  104   Seema   56000        672000     Pune         NaN
e  105  Preeti   35000    Programmer     Pune         NaN

In [55]:
#Display top 3 records
df.head(3)

   eid   ename  salary annual_salary
a  101    Ajay   14000        168000
b  102   Vinay   45000        540000
c  105  Preeti   35000    Programmer

In [56]:
#Display last 5 records
df_combined.tail()

   eid   ename  salary annual_salary location designation
d  104   Seema   56000        672000     Pune         NaN
e  105  Preeti   35000    Programmer     Pune         NaN
g  107   Rohit   45000        540000     Pune      Tester
h  108   Teena   36000        432000     Pune      Tester
i  109   Kiran   56000        672000     Pune      Tester

In [58]:
df_combined.salary.mean()

np.float64(40250.0)

In [59]:
df_combined.salary.max()

56000

In [60]:
df_combined.salary.min()

14000

In [61]:
df_combined.salary.sum()

np.int64(322000)

In [62]:
df_combined.salary.std()

13646.035531035588

In [63]:
df_combined.salary.mode() #Most frequently occurring value

0    35000
1    45000
2    56000
Name: salary, dtype: int64

In [64]:
df_combined.salary.median()  #After sorting pick the middle value

40500.0