In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars93.csv')

In [3]:
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,4038500,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,4100000,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,4776500,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,4653500,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,5473500,20,Driver & Passenger,168,5,30.0,15.0

In [4]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

In [5]:
print("Rows : ",df.shape[0])
print("Columns : ",df.shape[1])

Rows :  93
Columns :  10

In [6]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='object')

In [7]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,9.300000e+01,93.000000,93.000000,93.000000,91.000000,82.000000
mean,3.999484e+06,22.365591,143.827957,5.086022,27.829670,13.890244
std,1.980183e+06,5.619812,52.374410,1.038979,2.989072,2.997967
min,1.517000e+06,15.000000,55.000000,2.000000,19.000000,6.000000
25%,2.501000e+06,18.000000,103.000000,4.000000,26.000000,12.000000
50%,3.628500e+06,21.000000,140.000000,5.000000,27.500000,14.000000
75%,4.776500e+06,25.000000,170.000000,6.000000,30.000000,15.000000
max,1.268950e+07,46.000000,300.000000,8.000000,36.000000,22.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     int64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(2), int64(4), object(4)
memory usage: 7.4+ KB

In [9]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [10]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [11]:
x = df['Rear.seat.room'].median()

In [12]:
df['Rear.seat.room'] = df['Rear.seat.room'].fillna(value=x)

In [13]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room      11
dtype: int64

In [14]:
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [15]:
df['Luggage.room'].median()

14.0

In [16]:
x = df['Luggage.room'].median()

In [17]:
df['Luggage.room'] = df['Luggage.room'].fillna(value=x)

In [18]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [19]:
df['AirBags'].mode()

0    Driver only
Name: AirBags, dtype: object

In [20]:
x = df['AirBags'].mode()[0]

In [21]:
df['AirBags'] = df['AirBags'].fillna(value=x)

In [22]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

In [23]:
#Normalization
from sklearn.preprocessing import MinMaxScaler

In [24]:
min_max = MinMaxScaler()

In [58]:
df.Price.min()

1517000

In [59]:
df['Price'].max()

12689500

## Add the new normalized column into our existing dataframe

In [61]:
price_normalized = (
    (df['Price'] - df['Price'].min()) /
    (df['Price'].max() - df['Price'].min())
)

df['price_normalized'] = price_normalized

In [62]:
df[['Price', 'price_normalized']].head()

     Price  price_normalized
0  3259500          0.155963
1  6949500          0.486239
2  5965500          0.398165
3  7728500          0.555963
4  6150000          0.414679

## Performing Standardization on Horse Power

In [63]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

df['Price_standardized'] = std_scaler.fit_transform(df[['Price']])

In [65]:
hoursepower_std = std_scaler.fit_transform(df[['Horsepower']])

In [66]:
hoursepower_std.min()

np.float64(-1.705210877485415)

In [67]:
hoursepower_std.max()

np.float64(2.998000579179055)

In [68]:
df['Horsepower_Std'] = hoursepower_std

## Data Encoding - One-Hot Encoding

In [69]:
df_encoded = pd.get_dummies(df)

In [70]:
df_encoded.shape

(93, 143)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        93 non-null     object
 1   Model               93 non-null     object
 2   Type                93 non-null     object
 3   Price               93 non-null     int64
 4   MPG.city            93 non-null     int64
 5   AirBags             93 non-null     object
 6   Horsepower          93 non-null     int64
 7   Passengers          93 non-null     int64
 8   Rear.seat.room      93 non-null     float64
 9   Luggage.room        93 non-null     float64
 10  type_encoded        93 non-null     int64
 11  price_normalized    93 non-null     float64
 12  Price_standardized  93 non-null     float64
 13  Horsepower_Std      93 non-null     float64
dtypes: float64(5), int64(5), object(4)
memory usage: 10.3+ KB

In [72]:
len(df['Manufacturer'].unique())

32

In [73]:
len(df['Model'].unique())

93

In [74]:
len(df['Type'].unique())

6

In [75]:
len(df['AirBags'].unique())

2

In [76]:
2+6+93+32-4

129

In [77]:
129+12

141

In [78]:
df.shape[1]

14

In [79]:
12+133

145

In [80]:
df_encoded.shape

(93, 143)

In [81]:
df_encoded.columns

Index(['Price', 'MPG.city', 'Horsepower', 'Passengers', 'Rear.seat.room',
       'Luggage.room', 'type_encoded', 'price_normalized',
       'Price_standardized', 'Horsepower_Std',
       ...
       'Model_Town_Car', 'Model_Vision', 'Type_Compact', 'Type_Large',
       'Type_Midsize', 'Type_Small', 'Type_Sporty', 'Type_Van',
       'AirBags_Driver & Passenger', 'AirBags_Driver only'],
      dtype='object', length=143)

In [82]:
df.AirBags.unique()

array(['Driver only', 'Driver & Passenger'], dtype=object)

In [83]:
df.Type.unique()

array(['Small', 'Midsize', 'Compact', 'Large', 'Sporty', 'Van'],
      dtype=object)

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
label_encoder = LabelEncoder()

In [86]:
df_encoded = label_encoder.fit_transform(df["Type"])

In [87]:
df_encoded

array([3, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 4, 2, 5, 5, 1, 4, 1, 0, 1,
       3, 3, 0, 5, 2, 4, 3, 1, 3, 3, 0, 4, 4, 5, 2, 1, 3, 4, 4, 3, 0, 3,
       3, 4, 2, 2, 2, 2, 2, 1, 3, 3, 0, 5, 4, 0, 2, 4, 2, 3, 2, 3, 0, 5,
       2, 0, 2, 5, 1, 4, 3, 0, 4, 2, 1, 0, 3, 3, 3, 0, 3, 3, 4, 2, 5, 3,
       5, 0, 4, 0, 2])

In [88]:

df['type_encoded'] = df_encoded

In [89]:
 df_encoded

array([3, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 4, 2, 5, 5, 1, 4, 1, 0, 1,
       3, 3, 0, 5, 2, 4, 3, 1, 3, 3, 0, 4, 4, 5, 2, 1, 3, 4, 4, 3, 0, 3,
       3, 4, 2, 2, 2, 2, 2, 1, 3, 3, 0, 5, 4, 0, 2, 4, 2, 3, 2, 3, 0, 5,
       2, 0, 2, 5, 1, 4, 3, 0, 4, 2, 1, 0, 3, 3, 3, 0, 3, 3, 4, 2, 5, 3,
       5, 0, 4, 0, 2])