In [1]:
import pandas as pd
import numpy as np

In [2]:
#Empty
df = pd.DataFrame()

In [3]:
arr = np.arange(1,21).reshape(4,5)
df = pd.DataFrame(arr)

In [4]:
data = {"roll_no":[101,102,103,104,105],"name":["Ajay","Sanjay","Nisha","Nidhi","Suraj"],"percentage":[78,89,56,71,77]}
df = pd.DataFrame(data)

In [5]:
df

   roll_no    name  percentage
0      101    Ajay          78
1      102  Sanjay          89
2      103   Nisha          56
3      104   Nidhi          71
4      105   Suraj          77

In [6]:
df.roll_no #columns

0    101
1    102
2    103
3    104
4    105
Name: roll_no, dtype: int64

In [7]:
df['roll_no']  #columns

0    101
1    102
2    103
3    104
4    105
Name: roll_no, dtype: int64

In [8]:
df[['roll_no','name']]   #columns

   roll_no    name
0      101    Ajay
1      102  Sanjay
2      103   Nisha
3      104   Nidhi
4      105   Suraj

In [9]:
df.iloc[0] # row

roll_no        101
name          Ajay
percentage      78
Name: 0, dtype: object

In [10]:
df.loc['a'] # row

KeyError: 'a'

In [11]:
df.iloc[[0,2,3]] # row

   roll_no   name  percentage
0      101   Ajay          78
2      103  Nisha          56
3      104  Nidhi          71

In [ ]:
# Adding a new columns

In [ ]:
data = {"location":["Pune","Mumbai","Nagpur"]}
df_location = pd.DataFrame(data)

In [1]:
import pandas as pd

In [3]:
data ={"Name":["John","Peter","Lisa"],
    "Age":[25,28,31],
       "Salary":[30000,45000,25000]
}


df = pd.DataFrame(data)

print(df)

    Name  Age  Salary
0   John   25   30000
1  Peter   28   45000
2   Lisa   31   25000

In [4]:
df.iloc[0] # row

Name       John
Age          25
Salary    30000
Name: 0, dtype: object