In [49]:
import numpy as np

li = [100, 2000, 300]

avg_salary = np.mean(li)
print("Average Salary =", avg_salary)

Average Salary = 800.0

In [50]:
import numpy as np

li = [100, 2000, 300]

arr = np.array(li)
print(arr.mean())

800.0

In [51]:
import pandas as pd

In [52]:
pizza_sel = pd.Series([12,30,45,60,110])
pizza_sel

0     12
1     30
2     45
3     60
4    110
dtype: int64

In [53]:
import pandas as pd

pizza_sel = pd.Series(
    [12, 30, 45, 60, 110],
    index=["Mon", "Tue", "Wed", "Thu", "Sun"]
)

print(pizza_sel["Sun"])

110

In [54]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "Rupesh", "Pooja", "Priyanka", "Aadesh", "Sanket",
        "Sonali", "Tanuja", "Priti", "Anuj", "Pranav",
        "Seema", "Tanvi", "Rahul", "Neha", "Amit",
        "Sneha", "Vikas", "Kiran", "Rohan", "Swati"
    ],
    "Age": [
        25, 28, 30, 24, 27,
        26, 29, 23, 31, 32,
        28, 22, 35, 27, 30,
        26, 33, 29, 24, 31
    ],
    "Salary": [
        32000, 45000, 35000, 25000, 34000,
        26000, 35000, 29000, 27000, 42000,
        32000, 12000, 50000, 38000, 40000,
        36000, 47000, 33000, 28000, 39000
    ]
})

print(df)

        Name  Age  Salary
0     Rupesh   25   32000
1      Pooja   28   45000
2   Priyanka   30   35000
3     Aadesh   24   25000
4     Sanket   27   34000
5     Sonali   26   26000
6     Tanuja   29   35000
7      Priti   23   29000
8       Anuj   31   27000
9     Pranav   32   42000
10     Seema   28   32000
11     Tanvi   22   12000
12     Rahul   35   50000
13      Neha   27   38000
14      Amit   30   40000
15     Sneha   26   36000
16     Vikas   33   47000
17     Kiran   29   33000
18     Rohan   24   28000
19     Swati   31   39000

In [55]:
print(df.columns)

Index(['Name', 'Age', 'Salary'], dtype='object')

In [56]:
df.head()      # First 5 rows
df.tail()      # Last 5 rows
df.sample(2)   # Random 2 rows

     Name  Age  Salary
11  Tanvi   22   12000
1   Pooja   28   45000

In [57]:
df.shape     #Rows aur Columns

(20, 3)

In [58]:
print((df["Salary"] < 25000).sum())

1

In [59]:
print("Rows =", df.shape[0])
print("Columns =", df.shape[1])

Rows = 20
Columns = 3

In [60]:
df.columns  #Column Names

Index(['Name', 'Age', 'Salary'], dtype='object')

In [61]:
df.columns.tolist()

['Name', 'Age', 'Salary']

In [62]:
df.index  #Index (Row Labels)

RangeIndex(start=0, stop=20, step=1)

In [63]:
df.dtypes  # Data Types

Name      object
Age        int64
Salary     int64
dtype: object

In [64]:
df.info()  #Complete Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    20 non-null     object
 1   Age     20 non-null     int64
 2   Salary  20 non-null     int64
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes

In [65]:
df.describe()   #Statistica

             Age        Salary
count  20.000000     20.000000
mean   28.000000  34250.000000
std     3.479262   8704.959264
min    22.000000  12000.000000
25%    25.750000  28750.000000
50%    28.000000  34500.000000
75%    30.250000  39250.000000
max    35.000000  50000.000000

In [48]:
df["Salary"]  #Single Column

0     32000
1     45000
2     35000
3     25000
4     34000
5     26000
6     35000
7     29000
8     27000
9     42000
10    32000
11    12000
12    50000
13    38000
14    40000
15    36000
16    47000
17    33000
18    28000
19    39000
Name: Salary, dtype: int64

In [26]:
df[["Name", "Salary"]]    #Multiple Columns

        Name  Salary
0     Rupesh   32000
1      Pooja   45000
2   Priyanka   35000
3     Aadesh   25000
4     Sanket   34000
5     Sonali   26000
6     Tanuja   35000
7      Priti   29000
8       Anuj   27000
9     Pranav   42000
10     Seema   32000
11     Tanvi   12000
12     Rahul   50000
13      Neha   38000
14      Amit   40000
15     Sneha   36000
16     Vikas   47000
17     Kiran   33000
18     Rohan   28000
19     Swati   39000

In [27]:
df["Salary"].max()   # Highest Salary

50000

In [28]:
df["Salary"].min()  #Lowest Salary

12000

In [29]:
df["Salary"].mean()  #Average Salary

np.float64(34250.0)

In [30]:
df["Salary"].sum()  #Total Salary

np.int64(685000)

In [31]:
df["Salary"].count()  #Count Records

np.int64(20)

In [32]:
len(df)

20

# Filtering

In [33]:
df[df["Salary"] > 30000]

        Name  Age  Salary
0     Rupesh   25   32000
1      Pooja   28   45000
2   Priyanka   30   35000
4     Sanket   27   34000
6     Tanuja   29   35000
9     Pranav   32   42000
10     Seema   28   32000
12     Rahul   35   50000
13      Neha   27   38000
14      Amit   30   40000
15     Sneha   26   36000
16     Vikas   33   47000
17     Kiran   29   33000
19     Swati   31   39000

In [34]:
df[df["Salary"] < 25000]

     Name  Age  Salary
11  Tanvi   22   12000

In [35]:
df[df["Age"] > 25]

        Name  Age  Salary
1      Pooja   28   45000
2   Priyanka   30   35000
4     Sanket   27   34000
5     Sonali   26   26000
6     Tanuja   29   35000
8       Anuj   31   27000
9     Pranav   32   42000
10     Seema   28   32000
12     Rahul   35   50000
13      Neha   27   38000
14      Amit   30   40000
15     Sneha   26   36000
16     Vikas   33   47000
17     Kiran   29   33000
19     Swati   31   39000

# Sorting

In [37]:
df.sort_values("Salary")   #ascending

        Name  Age  Salary
11     Tanvi   22   12000
3     Aadesh   24   25000
5     Sonali   26   26000
8       Anuj   31   27000
18     Rohan   24   28000
7      Priti   23   29000
0     Rupesh   25   32000
10     Seema   28   32000
17     Kiran   29   33000
4     Sanket   27   34000
2   Priyanka   30   35000
6     Tanuja   29   35000
15     Sneha   26   36000
13      Neha   27   38000
19     Swati   31   39000
14      Amit   30   40000
9     Pranav   32   42000
1      Pooja   28   45000
16     Vikas   33   47000
12     Rahul   35   50000

In [38]:
df.sort_values("Salary", ascending=False)   # descending

        Name  Age  Salary
12     Rahul   35   50000
16     Vikas   33   47000
1      Pooja   28   45000
9     Pranav   32   42000
14      Amit   30   40000
19     Swati   31   39000
13      Neha   27   38000
15     Sneha   26   36000
2   Priyanka   30   35000
6     Tanuja   29   35000
4     Sanket   27   34000
17     Kiran   29   33000
0     Rupesh   25   32000
10     Seema   28   32000
7      Priti   23   29000
18     Rohan   24   28000
8       Anuj   31   27000
5     Sonali   26   26000
3     Aadesh   24   25000
11     Tanvi   22   12000

# Specific Row

In [41]:
# first row

df.iloc[0]

Name      Rupesh
Age           25
Salary     32000
Name: 0, dtype: object

In [42]:
# second row

df.iloc[1]

Name      Pooja
Age          28
Salary    45000
Name: 1, dtype: object

# Number of Dimensions

In [43]:
df.ndim

2

# Size

In [44]:
df.size

60